version: "3.3"

services:
  db:
    image: postgres:alpine
    ports:
      - "5431:5432"
    volumes:
      - queue_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: queue_db

volumes:
  queue_db_volume: {}
